nodeLinker: pnp

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

supportedArchitectures:
  os:
    - linux
    - darwin

yarnPath: .yarn/releases/yarn-3.1.1.cjs
